<?php

namespace App\Controller;

use Cake\Core\Configure;
use Cake\Event\Event;
use Cake\Network\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;


class MainController extends AppController
{
	public function isAuthorized($user) {
		return true;  
    }

    public function beforeFilter(Event $event)
    {
        $this->Auth->allow('index');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index() {
        $this->viewBuilder()->layout('frontpage');
	}
}


